[Fixes AB#566] Edit project screen
AMPnet/ampnet-crowdfunding-frontend pull request #142
Opened 2020-11-12 15:20 UTC by Skafec

To test:
Test if ROI works properly
Test if all data is being updated properly
Check if everything is linked correctly in form
Check if redirecting to from ‘’ path is setup right
Check if manage payments screen redirected from revenue share screen looks good

Done
Added redirecting from ‘’ to ‘offers’ (when we accessed site directly, we would still have that annoying route /dash where we would show offers but active link wasn’t highlighted)
Added placeholder image for project in project details
Added ROI to be 0 by default, if user doesn’t change value from 0 it is hidden on offers list and offer details screen

2020-11-12 19:54 UTC, mj-ampnet commented
I have added new info to the project but the "Update" button doesn't work
<img width="1206" alt="Screenshot 2020-11-12 at 20 53 26" src="https://user-images.githubusercontent.com/42938691/98989259-2899ff80-2529-11eb-9da8-7ab771e0fd38.png">

2020-11-12 20:33 UTC, Skafec commented
Yes, I know about that, @mj-ampnet .

Because of the new design I had to move buttons out of the form and I asked @mightymatth for help on how to hook
up buttons functionality properly now. I saw that functionality could be handled through form controls but I wanted to make
sure before experimenting 😄

2020-11-12 22:36 UTC, mj-ampnet commented
Excellent. Then keep on with it 😁

2020-11-13 13:31 UTC, mightymatth requested changes
![image](https://user-images.githubusercontent.com/13491551/99077306-d5718c80-25bc-11eb-9a8b-568689edd295.png)

Can you fix this "Update all" button that is going out of the screen?

Everything else seems fine!

2020-11-13 13:31 UTC, mightymatth commented on src/app/organizations/organization-details/manage-projects/manage-single-project/manage-single-project.component.html
> +                        {{ states.project.organization?.name }}
This is just a temporary fix because the backend doesn't return the organization when a project gets updated.

2020-11-13 13:31 UTC, mightymatth commented on src/app/organizations/organization-details/manage-projects/manage-single-project/manage-single-project.component.html
> -                                <ng-container *ngIf="(updateForm$ | async) as updateForm">
You already have the subscription at the beginning of the file so you can share it throughout the template.

2020-11-13 13:31 UTC, mightymatth commented on src/app/organizations/organization-details/manage-projects/manage-single-project/manage-single-project.component.ts
> -            const expectedInvest = this.currencyPipe.transform(project.expected_funding, 'EUR', 'symbol', '2.0');
As we talked, no need for having this in the form if the values won't be ever changed. This can be set in the template.

2020-11-13 13:31 UTC, mightymatth commented on src/app/organizations/organization-details/manage-projects/manage-single-project/manage-single-project.component.ts
> -                    roiTo: [project.roi.to, Validators.pattern('^[0-9]*$')],
Invalid pattern. Matches all numbers, but not decimals.

2020-11-13 13:31 UTC, mightymatth commented on src/app/shared/services/project/project.service.ts
> -    organization: Organization[];
This is not an array. Please, find out how to set template Typescript type checking for Angular inside templates (.html files). You would notice this on `{{ states.project.organization?.name }}` if you had this check.

2020-11-16 09:50 UTC, mightymatth approved these changes
Great!

2020-11-16 09:54 UTC, merged