[Fixes AB#685] Offers news
AMPnet/ampnet-crowdfunding-frontend pull request #159
Opened 2020-12-10 10:02 UTC by Skafec

Added news section on offer details screen

2020-12-10 11:25 UTC, githinho commented
The new version is live on staging.

2020-12-10 13:32 UTC, mightymatth requested changes

2020-12-10 13:32 UTC, mightymatth commented on src/app/offers/offer-details/offer-details.component.html
> +                <ng-container *ngIf="states.news != null">
if there are no news, markup will look like this:

```
<div class="left__news">
</div>
```

We don't want that. Remove ng-container and put `*ngIf="states.news != null"` on `div.left__news`.

2020-12-10 13:32 UTC, mightymatth commented on src/app/organizations/organization-details/manage-projects/manage-single-project/manage-single-project.component.scss
> +                cursor: pointer;
If something is clickable, it should be either a button or anchor link ("a" tag).

It's good to follow this: If something is clickable, and it's not a button, wrap it in anchor tag, set empty routerLink and set click listener:

```
<a [routerLink]="" (click)="openBeer($event)">
  <div>Anything clickable</div>
</a>
```

This way, this element will be clickable, visible in text readers, and have a pointer as a cursor on the desktop.

2020-12-10 14:59 UTC, mightymatth commented
If we have link previews, why don't we present the entire link preview (image, title, description)?

Consider having link like this: https://www.index.hr/vijesti/clanak/pitali-smo-struku-o-spomeniku-domovini-bukvalan-je-preskup-i-na-krivom-mjestu/2237703.aspx?index_tid=76661

Its preview (e.g. on Twitter) looks like this:

![image](https://user-images.githubusercontent.com/13491551/101787862-d801cc00-3aff-11eb-9df7-810d982614b6.png)

Meaning that image, title and description can be fetched from our link preview service.
So my idea is to make a list of items like this:

![image](https://user-images.githubusercontent.com/13491551/101788330-421a7100-3b00-11eb-8e50-ac52e954da3b.png)

where each item will be clickable which will redirect the user to the given URL. If we already have these data from our link preview service, why not use them.

@filipdujmusic , can you think about this idea; do we need it now, how the items might look like, etc. I'm just mentioning it here to discuss it.

2020-12-13 08:49 UTC, filipdujmusic commented
> If we have link previews, why don't we present the entire link preview (image, title, description)?
> 
> Consider having link like this: https://www.index.hr/vijesti/clanak/pitali-smo-struku-o-spomeniku-domovini-bukvalan-je-preskup-i-na-krivom-mjestu/2237703.aspx?index_tid=76661
> 
> Its preview (e.g. on Twitter) looks like this:
> 
> ![image](https://user-images.githubusercontent.com/13491551/101787862-d801cc00-3aff-11eb-9df7-810d982614b6.png)
> 
> Meaning that image, title and description can be fetched from our link preview service.
> So my idea is to make a list of items like this:
> 
> ![image](https://user-images.githubusercontent.com/13491551/101788330-421a7100-3b00-11eb-8e50-ac52e954da3b.png)
> 
> where each item will be clickable which will redirect the user to the given URL. If we already have these data from our link preview service, why not use them.
> 
> @filipdujmusic , can you think about this idea; do we need it now, how the items might look like, etc. I'm just mentioning it here to discuss it.

@mightymatth why not? Your proposed layout looks good to me. I'm just trying to think one step ahead, if we are ever going to move link/file components to the right side of the offer details screen (to fill a white gap caused by large description size), would this layout fit in?

2020-12-13 21:04 UTC, mj-ampnet commented
Yes - keep this layout that @mightymatth suggested - it used to be implemented like this.a

2020-12-16 17:30 UTC, mj-ampnet commented
@Skafec what's happening with this feature? It would be good to have it for the launch... It shouldn't be too difficult to implement... The link preview service gives you all the data you need. If you're worried about the design, contact me on slack and we'll discuss.

2020-12-17 10:41 UTC, mightymatth approved these changes
It's OK for now. A new design will be made in the next pull request.

2020-12-17 10:41 UTC, merged