404 implement share offer on facebook button
AMPnet/ampnet-crowdfunding-frontend pull request #90
Opened 2020-09-09 12:58 UTC by mdrusko1

2020-09-09 16:43 UTC, mightymatth requested changes

2020-09-09 16:43 UTC, mightymatth commented on package.json
> +    "ngx-facebook": "^3.0.0-0",
As we previously spoke, we don't need the entire facebook library for angular just to have a link to share. 
When adding a new library, we need to wisely choose whether we reeeeally need this library or not. Our application footprint (bundle size) is currently around 12MB.

Very simple solution:

in `component.ts`:
```typescript
    currentLocation = encodeURIComponent(window.location.href);
```

In `.component.html`, for Facebook and Twitter:

```angular
<a href="https://www.facebook.com/sharer/sharer.php?u={{ currentLocation }}"
    target="_blank">
    <i class="fab fa-facebook-f"></i>
</a>

<a href="https://twitter.com/intent/tweet?url={{ currentLocation }}"
    target="_blank">
    <i class="fab fa-twitter"></i>
</a>
```

2020-09-10 09:18 UTC, mightymatth requested changes
Ready for QA. @filipdujmusic 
Note: Share on Facebook will display an error, but that's OK. Once it gets on the staging environment, it will display properly.

2020-09-10 14:49 UTC, filipdujmusic commented
QA OK! @mightymatth

2020-09-14 09:10 UTC, mightymatth approved these changes

2020-09-14 09:10 UTC, merged