[Fixes AB#434] Spinner added
AMPnet/ampnet-crowdfunding-frontend pull request #94
Opened 2020-09-11 10:13 UTC by Skafec

Added spinner when project wallet is being initiated with Arkane

2020-09-11 12:48 UTC, mightymatth commented on src/app/manage-projects/manage-single-project/manage-single-project.component.ts
> +            SpinnerUtil.showSpinner();
This way, after clicking the button to create a project wallet, there will be no spinner until our backend returns response of `this.walletService.createProjectWalletTransaction(this.project.uuid)`. This is an asynchronous method.
Set this line at the beginning of `createProjectWallet()` method (between lines 68 and 69).

2020-09-11 14:52 UTC, Skafec commented
Update: In order for Spinner to show when it is added at the start of method, I had to move hideSpinner method out of error handlers. Because we have a async method, code would continue to run and it would get to hideSpinner method inside of fetchAllData too soon.

2020-09-15 21:18 UTC, mightymatth requested changes

2020-09-15 21:18 UTC, mightymatth commented on src/app/manage-projects/manage-single-project/manage-single-project.component.ts
> +            SpinnerUtil.hideSpinner();
This line doesn't make sense. subscription from line 57 to 69 represents asynchronous call
Think logically. This here means that you:

1. show spinner, 
2. synchronously start async call (finishes immediately), 
3. hide spinner. 

Practically, this spinner won't be even visible. If it fixes closing some orphan spinner from somewhere else, it's unintentional. Fix closing the right spinner on the place where it should be closed.

2020-09-16 07:12 UTC, Skafec commented
Oh so that's why we had unnecessary spinner showing when project had active wallet.

Now fetchAllData() method is cleaned up from spinners and all the spinners are being closed on other
function calls inside it.

2020-09-16 07:37 UTC, mightymatth commented on src/app/manage-projects/manage-single-project/manage-single-project.component.ts
> -            SpinnerUtil.showSpinner();
I didn't mean that spinners should be removed from `fetchAllData()`, but should be set properly: 
1. on the entrance of the function
2. in every possible callback where it should be closed (all callbacks that finishes data fetch; success and error callbacks).

2020-09-16 07:47 UTC, mightymatth commented on src/app/manage-projects/manage-single-project/manage-single-project.component.ts
>                      displayBackendError(err);
use `hideSpinnerAndDisplayError()` and remove `hideSpinner()` from below.

2020-09-23 12:29 UTC, mightymatth commented
Will be fixed in another branch

2020-09-23 12:29 UTC, closed without merging