After verify transaction navigate to wallet screen
AMPnet/ampnet-crowdfunding-frontend pull request #98
Opened 2020-09-15 09:56 UTC by mdrusko1

2020-09-15 21:21 UTC, mightymatth requested changes

2020-09-15 21:21 UTC, mightymatth commented on src/app/offers/verify-sign-offer/verify-sign-offer.component.ts
> +            this.navigateToWalletScreen();
Make this oneliner. You don't need to extract a route navigation to a new method. You can navigate in `then` callback directly.

2020-09-16 07:31 UTC, mightymatth approved these changes

2020-09-16 07:39 UTC, mightymatth requested changes
Ready for QA. @filipdujmusic

2020-09-23 10:09 UTC, closed without merging

2020-09-23 10:09 UTC, mj-ampnet commented
Task solved