[Fixes AB#70] Facebook sing up fixed | added FcbApp Provider ID
AMPnet/ampnet-crowdfunding-frontend pull request #99
Opened 2020-09-15 13:18 UTC by mdrusko1

2020-09-15 21:06 UTC, mightymatth requested changes

2020-09-15 21:06 UTC, mightymatth commented on src/app/app.module.ts
> +                provider: new FacebookLoginProvider('611379136173563'),
google how Angular utilise environment variables and set Google and Facebook App IDs there. We don't have any example here, but look over the Internet how to do it.

2020-09-15 21:06 UTC, mightymatth commented on src/app/authentication/sign-up/sign-up.component.ts
> +                this.loginService.socialLogin(provider, SocialRes.authToken)
Can you go over this entire method and see which things can be made better. We'll try to fix some thing by the way. If you don't see any, we'll do it together.

2020-09-16 08:09 UTC, mightymatth requested changes
Ready for QA. @filipdujmusic 

Try:
* signup with Facebook,
* login with Facebook.

Also, to be sure, you also could try:
* signup with Google,
* login with Facebook.

EDIT: Not ready yet. I'll notify you again.

2020-09-22 14:58 UTC, mj-ampnet approved these changes

2020-09-22 15:04 UTC, mj-ampnet approved these changes

2020-09-22 15:05 UTC, mj-ampnet approved these changes

2020-09-22 15:05 UTC, merged